language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE andela;" -U postgres
  - psql -c "CREATE USER andela WITH PASSWORD 'andela123';" -U postgres
<<<<<<< HEAD
=======
  - npm run create
>>>>>>> feat(update car status): update car advert status [Finishes #166726256]
  - npm run build
script:
  - npm run test
after_success:
  - npm run coveralls